# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
options:
  implicit_slide_ends: true
export:
  dimensions:
    columns: 70
    rows: 20
  pdf:
    fonts:
      normal: /usr/share/fonts/MapleMono-NF-unhinted/MapleMono-NF-Regular.ttf
      italic: /usr/share/fonts/MapleMono-NF-unhinted/MapleMono-NF-Italic.ttf
      bold: /usr/share/fonts/MapleMono-NF-unhinted/MapleMono-NF-Bold.ttf
      bold_italic: /usr/share/fonts/MapleMono-NF-unhinted/MapleMono-NF-BoldItalic.ttf
