# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
options:
  implicit_slide_ends: true
export:
  dimensions:
    columns: 90
    rows: 25
