version = "1.1.14"

[format]
dedup = true
workspace = "{id} {clients}"
client = "{icon}"
client_dup = "{icon} {counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_active = "{icon}"


[class]
"[Nn]emo" = "󰷏"
"[Pp]cmanfm" = "󰷏"
"DEFAULT" = "󰘔"
"(?i)Alacritty" = "󰆍"
"[Ff]irefox" = "󰈹"
"nm-connection-editor" = ""
"[Ss]team" = "󰓓"
"[Ss]potify" = "󰓇"
"snappergui" = ""
"[Zz]athura" = "󰂾"
"[Vv]lc" = "󰕼"
"[Ee]npass" = "󰌿"

[title_in_class."(?i)alacritty"]
"(?i)NVIM" = ""
"(?i)aerc" = "󰻤"
"(?i)khal" = "󰃭"
"(?i)ncspot" = "󰓇"
"(?i)ranger" = "󰷏"

[exclude]
"" = "^$"             # prevent displaying clients with empty class
"Rofi" = "rofi - run"
1 = "1"
2 = "2"
3 = "3"
4 = "4"
5 = "5"
6 = "6"
7 = "7"
8 = "8"
9 = "9"
