[terminal.shell]
program = "/bin/fish"
args = ["-l"]

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 1.00
blur = false 

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrains Mono Nerd Font" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 12
builtin_box_drawing = true 

[colors.primary]
background = "#282c34"
foreground = "#dcdfe4"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#dcdfe4"

[colors.bright]
black = "#7f848e"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#0184bc"
magenta = "#a626a4"
cyan = "#0997b3"
white = "#fafafa"

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false

[general]
live_config_reload = true

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
