[packages]
[packages.linux]
[packages.linux.arch]
[packages.linux.arch.oneill]
packages = [
  'amd-ucode',
  'base',
  'btrfs-assistant',
  'btrfs-progs',
  'cups',
  'dosfstools',
  'efibootmgr',
  'inotify-tools',
  'snap-pac',
  'linux',
  'linux-firmware',
  'linux-headers',
  'linux-lts',
  'linux-lts-headers',
  'linux-zen',
  'linux-zen-headers',
  'networkmanager',
  'ntfs-3g',
  'snapper',
  'sudo',
  'syslinux',
  'thefuck',
  'vulkan-radeon',
  'xf86-video-amdgpu',
  'xf86-video-ati',
  'xorg-server',
  'xorg-xhost',
  'xorg-xinit',
  'xorg-xrandr',
  'yay-bin',
  'zram-generator',
]

[packages.linux.arch.tealc]
packages = [
  'accountsservice',
  'alsa-firmware',
  'alsa-plugins',
  'alsa-utils',
  'amd-ucode',
  'ark',
  'awesome-terminal-fonts',
  'base',
  'bash-completion',
  'bind',
  'bluedevil',
  'bluez',
  'bluez-hid2hci',
  'bluez-libs',
  'bluez-obex',
  'bluez-utils',
  'breeze-gtk',
  'btop',
  'btrfs-progs',
  'cachy-update',
  'cachyos-emerald-kde-theme-git',
  'cachyos-fish-config',
  'cachyos-gaming-applications',
  'cachyos-gaming-meta',
  'cachyos-hello',
  'cachyos-hooks',
  'cachyos-iridescent-kde',
  'cachyos-kde-settings',
  'cachyos-kernel-manager',
  'cachyos-keyring',
  'cachyos-mirrorlist',
  'cachyos-nord-kde-theme-git',
  'cachyos-packageinstaller',
  'cachyos-plymouth-bootanimation',
  'cachyos-rate-mirrors',
  'cachyos-settings',
  'cachyos-themes-sddm',
  'cachyos-v3-mirrorlist',
  'cachyos-v4-mirrorlist',
  'cachyos-wallpapers',
  'cantarell-fonts',
  'char-white',
  'chwd',
  'cpupower',
  'cryptsetup',
  'cups',
  'device-mapper',
  'diffutils',
  'dmidecode',
  'dmraid',
  'dnsmasq',
  'dolphin',
  'dosfstools',
  'duf',
  'e2fsprogs',
  'efitools',
  'egl-wayland',
  'ethtool',
  'exfatprogs',
  'pavucontrol',
  'openssh',
  'f2fs-tools',
  'ffmpegthumbnailer',
  'ffmpegthumbs',
  'filelight',
  'fsarchiver',
  'fwupd',
  'glances',
  'gst-libav',
  'gst-plugin-pipewire',
  'gst-plugins-bad',
  'gst-plugins-ugly',
  'gwenview',
  'haruna',
  'hdparm',
  'hwdetect',
  'hwinfo',
  'iptables-nft',
  'iwd',
  'jfsutils',
  'kcalc',
  'kde-gtk-config',
  'kdegraphics-thumbnailers',
  'kdeplasma-addons',
  'kdialog',
  'kinfocenter',
  'kio-admin',
  'kscreen',
  'kwallet-pam',
  'kwalletmanager',
  'less',
  'lib32-nvidia-utils',
  'lib32-opencl-nvidia',
  'lib32-vulkan-icd-loader',
  'libdvdcss',
  'libgsf',
  'libopenraw',
  'libva-nvidia-driver',
  'linux-cachyos',
  'linux-cachyos-headers',
  'linux-cachyos-lts',
  'linux-cachyos-lts-headers',
  'linux-cachyos-lts-nvidia-open',
  'linux-cachyos-nvidia-open',
  'linux-firmware',
  'logrotate',
  'lsb-release',
  'lsscsi',
  'lvm2',
  'man-pages',
  'mdadm',
  'meld',
  'mesa-utils',
  'mkinitcpio',
  'modemmanager',
  'mtools',
  'netctl',
  'networkmanager',
  'networkmanager-openvpn',
  'nfs-utils',
  'nilfs-utils',
  'noto-fonts',
  'noto-fonts-cjk',
  'noto-fonts-emoji',
  'nss-mdns',
  'nvidia-settings',
  'nvidia-utils',
  'octopi',
  'opencl-nvidia',
  'os-prober',
  'partitionmanager',
  'paru',
  'perl',
  'phonon-qt6-vlc',
  'pipewire-alsa',
  'pipewire-pulse',
  'pkgfile',
  'plasma-browser-integration',
  'plasma-desktop',
  'plasma-firewall',
  'plasma-login-manager',
  'plasma-nm',
  'plasma-pa',
  'plasma-systemmonitor',
  'plasma-thunderbolt',
  'plocate',
  'plymouth',
  'plymouth-kcm',
  'poppler-glib',
  'power-profiles-daemon',
  'powerdevil',
  'pv',
  'python-defusedxml',
  'python-packaging',
  'rebuild-detector',
  's-nail',
  'sg3_utils',
  'sof-firmware',
  'spectacle',
  'sudo',
  'sysfsutils',
  'texinfo',
  'konsole',
  'limine',
  'limine-mkinitcpio-hook',
  'limine-snapper-sync',
  'snapper',
  'cachyos-snapper-support',
  'btrfs-assistant',
  'limine',
  'ttf-bitstream-vera',
  'ttf-dejavu',
  'ttf-liberation',
  'ttf-meslo-nerd',
  'ttf-opensans',
  'upower',
  'usb_modeswitch',
  'usbutils',
  'vlc-plugins-all',
  'vulkan-icd-loader',
  'which',
  'wpa_supplicant',
  'xdg-user-dirs',
  'xdg-utils',
  'xfsprogs',
  'xl2tpd',
  'xsettingsd',
  'yay-bin',
]
